export const FETCH_CLIENTINFOPERSONAL_REQUEST = "FETCH_CLIENTINFOPERSONAL_REQUEST";
export const FETCH_CLIENTINFOPERSONAL_SUCCESS = "FETCH_CLIENTINFOPERSONAL_SUCCESS";
export const FETCH_CLIENTINFOPERSONAL_FAILURE = "FETCH_CLIENTINFOPERSONAL_FAILURE";

export const UPDATE_CLIENTINFOPERSONAL_REQUEST = "UPDATE_CLIENTINFOPERSONAL_REQUEST";
export const UPDATE_CLIENTINFOPERSONAL_SUCCESS = "UPDATE_CLIENTINFOPERSONAL_SUCCESS";
export const UPDATE_CLIENTINFOPERSONAL_FAILURE = "UPDATE_CLIENTINFOPERSONAL_FAILURE";

export const CREATE_CLIENTINFOPERSONAL_REQUEST = "CREATE_CLIENTINFOPERSONAL_REQUEST";
export const CREATE_CLIENTINFOPERSONAL_SUCCESS = "CREATE_CLIENTINFOPERSONAL_SUCCESS";
export const CREATE_CLIENTINFOPERSONAL_FAILURE = "CREATE_CLIENTINFOPERSONAL_FAILURE";

export const DELETE_CLIENTINFOPERSONAL_REQUEST = "DELETE_CLIENTINFOPERSONAL_REQUEST";
export const DELETE_CLIENTINFOPERSONAL_SUCCESS = "DELETE_CLIENTINFOPERSONAL_SUCCESS";
export const DELETE_CLIENTINFOPERSONAL_FAILURE = "DELETE_CLIENTINFOPERSONAL_FAILURE";