export const FETCH_CLIENTPERSONALAPPROACH_REQUEST =
    "FETCH_CLIENTPERSONALAPPROACH_REQUEST";
export const FETCH_CLIENTPERSONALAPPROACH_SUCCESS =
    "FETCH_CLIENTPERSONALAPPROACH_SUCCESS";
export const FETCH_CLIENTPERSONALAPPROACH_FAILURE =
    "FETCH_CLIENTPERSONALAPPROACH_FAILURE";

export const UPDATE_CLIENTPERSONALAPPROACH_REQUEST =
    "UPDATE_CLIENTPERSONALAPPROACH_REQUEST";
export const UPDATE_CLIENTPERSONALAPPROACH_SUCCESS =
    "UPDATE_CLIENTPERSONALAPPROACH_SUCCESS";
export const UPDATE_CLIENTPERSONALAPPROACH_FAILURE =
    "UPDATE_CLIENTPERSONALAPPROACH_FAILURE";

export const CREATE_CLIENTPERSONALAPPROACH_REQUEST =
    "CREATE_CLIENTPERSONALAPPROACH_REQUEST";
export const CREATE_CLIENTPERSONALAPPROACH_SUCCESS =
    "CREATE_CLIENTPERSONALAPPROACH_SUCCESS";
export const CREATE_CLIENTPERSONALAPPROACH_FAILURE =
    "CREATE_CLIENTPERSONALAPPROACH_FAILURE";

export const DELETE_CLIENTPERSONALAPPROACH_REQUEST =
    "DELETE_CLIENTPERSONALAPPROACH_REQUEST";
export const DELETE_CLIENTPERSONALAPPROACH_SUCCESS =
    "DELETE_CLIENTPERSONALAPPROACH_SUCCESS";
export const DELETE_CLIENTPERSONALAPPROACH_FAILURE =
    "DELETE_CLIENTPERSONALAPPROACH_FAILURE";
