export const FETCH_INTERCEPTIONS_REQUEST = "FETCH_INTERCEPTIONS_REQUEST";
export const FETCH_INTERCEPTIONS_SUCCESS = "FETCH_INTERCEPTIONS_SUCCESS";
export const FETCH_INTERCEPTIONS_FAILURE = "FETCH_INTERCEPTIONS_FAILURE";
