export const FETCH_CLIENTCARES_REQUEST = "FETCH_CLIENTCARES_REQUEST";
export const FETCH_CLIENTCARES_SUCCESS = "FETCH_CLIENTCARES_SUCCESS";
export const FETCH_CLIENTCARES_FAILURE = "FETCH_CLIENTCARES_FAILURE";

export const UPDATE_CLIENTCARES_REQUEST = "UPDATE_CLIENTCARES_REQUEST";
export const UPDATE_CLIENTCARES_SUCCESS = "UPDATE_CLIENTCARES_SUCCESS";
export const UPDATE_CLIENTCARES_FAILURE = "UPDATE_CLIENTCARES_FAILURE";

export const CREATE_CLIENTCARES_REQUEST = "CREATE_CLIENTCARES_REQUEST";
export const CREATE_CLIENTCARES_SUCCESS = "CREATE_CLIENTCARES_SUCCESS";
export const CREATE_CLIENTCARES_FAILURE = "CREATE_CLIENTCARES_FAILURE";

export const DELETE_CLIENTCARES_REQUEST = "DELETE_CLIENTCARES_REQUEST";
export const DELETE_CLIENTCARES_SUCCESS = "DELETE_CLIENTCARES_SUCCESS";
export const DELETE_CLIENTCARES_FAILURE = "DELETE_CLIENTCARES_FAILURE";