export const FETCH_DEALS_REQUEST = "FETCH_DEALS_REQUEST";
export const FETCH_DEALS_SUCCESS = "FETCH_DEALS_SUCCESS";
export const FETCH_DEALS_FAILURE = "FETCH_DEALS_FAILURE";
export const ADD_DEALS_REQUEST = "ADD_DEALS_REQUEST";
export const ADD_DEALS_SUCCESS = "ADD_DEALS_SUCCESS";
export const ADD_DEALS_FAILURE = "ADD_DEALS_FAILURE";
